/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ex2;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public String getFactos() {
        return "Ronaldo >>>>>>>> Pessi";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new App().getFactos());
    }
}
